name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t practicesoftwaretesting .

    - name: Create .env file
      run: |
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
        echo "API_URL=${{ secrets.API_URL }}" >> .env
        echo "CUSTOMER_EMAIL=${{ secrets.CUSTOMER_EMAIL }}" >> .env
        echo "CUSTOMER_PASSWORD=${{ secrets.CUSTOMER_PASSWORD }}" >> .env

    - name: Run Playwright tests
      run: docker run --rm --env-file .env -e CI=true practicesoftwaretesting

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30